from typing import Any, Dict
from prompts.qualification_prompt import build_prompt
from utils.lead_schema import LEAD_FIELDS, missing_fields
from utils.lead_summary import build_lead_summary
from utils.json_utils import parse_json_robust
from utils.session_store import SessionStore
import os


class QualificationAgent:
    """Interactive lead qualification agent.

    Behavior:
    - Uses SessionStore to persist conversation history and collected lead fields
    - Asks one question at a time, generated by the model (or template fallback)
    - Stores answers and checks completion
    - Returns structured dict with next_question, collected_data, missing_fields, qualification_complete, lead_quality
    """

    def __init__(self, client: Any = None, sop: dict = None, memory: Any = None):
        self.client = client
        self.sop = sop
        # Expect memory to be a SessionStore or fallback to default
        if isinstance(memory, SessionStore):
            self.store = memory
        else:
            # allow passing session_id via env for simple use
            sid = os.getenv("SESSION_ID", "default")
            self.store = SessionStore(session_id=sid)

    def _choose_next_field(self, collected: Dict[str, str]) -> str:
        miss = missing_fields(collected)
        return miss[0] if miss else ""

    def _template_question_for(self, field: str, collected: Dict[str, str]) -> str:
        templates = {
            "business_type": "What kind of business or industry are you in?",
            "team_size": "How many people are on your team (approx.)?",
            "current_tools": "Which tools or platforms do you currently use for this workflow?",
            "customer_goals": "What are your main goals for this product/service?",
            "budget_interest": "Do you have a budget range or level of interest (low/medium/high)?",
            "contact_method": "What's your preferred contact method (email, phone, or other)?",
        }
        base = templates.get(field, f"Can you tell me about {field}?")
        # personalise if we have business_type
        if collected.get("business_type"):
            base = f"For your {collected.get('business_type')}, {base[0].lower() + base[1:]}"
        return base

    def handle(self, message: str) -> Dict:
        # Append incoming user message to history
        if message:
            self.store.append_message("user", message)

        collected = self.store.get_lead()

        # Determine if assistant previously asked for a specific field
        last_field, last_question = self.store.get_last_asked()

        # If the assistant had explicitly asked for a field, map this user message deterministically
        if last_field and message:
            msg_lower = message.strip().lower()
            # If user abandons or says goodbye, do not map
            if any(tok in msg_lower for tok in ("need to go", "i need to go", "bye", "goodbye", "got to go", "brb")):
                # keep last_asked as-is so we can re-ask later
                pass
            else:
                # detect explicit correction intent (user correcting a previous answer)
                correction_markers = ("actually", "i meant", "sorry", "correction", "instead", "no,")
                is_correction = any(msg_lower.startswith(m) or (" " + m + " ") in msg_lower for m in correction_markers)

                # helper: very small heuristic to infer which field a freeform answer is intended for
                def detect_field_from_text(text: str) -> str:
                    t = text.lower()
                    # numbers likely indicate team_size
                    if any(ch.isdigit() for ch in t):
                        return "team_size"
                    # contact info
                    if "@" in t or "email" in t or "phone" in t:
                        return "contact_method"
                    if any(k in t for k in ("shopify", "mailchimp", "hubspot", "salesforce", "zendesk", "drip")):
                        return "current_tools"
                    if any(k in t for k in ("budget", "$", "usd", "dollars", "price", "cost")):
                        return "budget_interest"
                    # business type heuristics
                    if any(k in t for k in ("clinic", "retailer", "e-comm", "ecommerce", "restaurant", "agency", "startup")):
                        return "business_type"
                    return ""

                inferred = ""
                if is_correction:
                    inferred = detect_field_from_text(message)

                # If inferred field differs from last_field, treat this as correction for a different field
                if inferred and inferred in LEAD_FIELDS and inferred != last_field:
                    # strip common correction prefixes when storing corrected values
                    cleaned = message.strip()
                    for p in ("actually", "i meant", "sorry", "correction", "instead", "no,"):
                        if cleaned.lower().startswith(p):
                            cleaned = cleaned[len(p):].strip(" ,.")
                            break
                    self.store.set_lead_field(inferred, cleaned)
                    # keep last_field as pending (so we will re-ask it next)
                else:
                    # Helper validators to avoid storing greetings or unrelated text
                    def is_generic_reply(text: str) -> bool:
                        t = text.strip().lower()
                        if not t:
                            return True
                        # numeric replies should not be considered generic
                        if any(ch.isdigit() for ch in t):
                            return False
                        gens = ("hi", "hello", "hey", "thanks", "thank you", "i'm interested", "im interested", "interested")
                        if any(t == g or t.startswith(g + " ") or g in t for g in gens):
                            return True
                        # very short non-numeric messages are likely generic
                        if len(t.split()) <= 2 and len(t) < 10:
                            return True
                        return False

                    def plausible_for_field(field: str, text: str) -> bool:
                        t = text.strip().lower()
                        if is_generic_reply(t):
                            return False
                        if field == "team_size":
                            return any(ch.isdigit() for ch in t)
                        if field == "contact_method":
                            return "@" in t or "email" in t or "phone" in t or any(d in t for d in ("call", "text", "sms"))
                        # for other fields, accept reasonably long replies
                        return len(t) >= 3

                    # Default: map to the last asked field only if reply looks plausible
                    if plausible_for_field(last_field, message):
                        self.store.set_lead_field(last_field, message.strip())
                        # clear last asked tracker
                        self.store.clear_last_asked()
                    else:
                        # Do not store ambiguous/generic replies; keep last_asked so we can re-ask
                        pass

        # Recompute collected and missing
        collected = self.store.get_lead()
        miss = missing_fields(collected)

        # If no missing fields, qualification complete
        qualification_complete = len(miss) == 0

        # If complete, build summary and return final payload
        if qualification_complete:
            summary = build_lead_summary(collected)
            self.store.append_message("assistant", "Qualification complete. Thank you.")
            return {
                "next_question": "",
                "collected_data": collected,
                "missing_fields": [],
                "qualification_complete": True,
                "lead_quality": summary.get("lead_quality"),
                "lead_summary": summary,
            }

        # Otherwise choose next field
        target = self._choose_next_field(collected)

        # If no target, we are complete (should be handled above)
        if not target:
            return {
                "next_question": "",
                "collected_data": collected,
                "missing_fields": miss,
                "qualification_complete": True,
                "lead_quality": build_lead_summary(collected).get("lead_quality"),
            }

        # Ask model to craft a single polite question for the target field, prefer structured JSON
        prompt = build_prompt(collected, target)
        system_prompt = "You are a helpful qualification assistant. Reply with valid JSON containing: {\"field_being_collected\": <field_name>, \"next_question\": <string>, \"updated_data\": { ... } }"
        raw = ""
        if self.client:
            raw = self.client.generate(system_prompt, prompt, temperature=0.25)

        # Parse the model output expecting JSON {field_being_collected, next_question, updated_data}
        parsed, err = parse_json_robust(raw)

        q = None
        field_from_model = None
        if parsed and not err:
            # Prefer model-provided field name if present and valid
            field_from_model = parsed.get("field_being_collected") or parsed.get("field")
            q = parsed.get("next_question")
            updated = parsed.get("updated_data") or {}
            if isinstance(updated, dict) and updated:
                # Merge updated data into lead (do not overwrite non-empty fields unless confirmed)
                for k, v in updated.items():
                    if v is None or v == "":
                        continue
                    # preserve existing unless different; prefer latest
                    self.store.set_lead_field(k, v)

        # Use model's field if it matches expected LEAD_FIELDS, else fallback to target
        if field_from_model and field_from_model in LEAD_FIELDS:
            chosen_field = field_from_model
        else:
            chosen_field = target

        # Choose question text: model-suggested or template
        if not q:
            q = self._template_question_for(chosen_field, collected)

        # Record the field we're asking for, so the next user reply maps deterministically
        self.store.set_last_asked(chosen_field, q)
        # Store assistant question in history
        self.store.append_message("assistant", q)

        return {
            "next_question": q,
            "collected_data": collected,
            "missing_fields": miss,
            "qualification_complete": False,
            "lead_quality": build_lead_summary(collected).get("lead_quality"),
        }

